"""empty message

Revision ID: 148d016ef2a3
Revises: 74c8228232c9
Create Date: 2024-04-06 15:29:15.882851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '148d016ef2a3'
down_revision: Union[str, None] = '74c8228232c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tokens_code'), 'tokens', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tokens_code'), table_name='tokens')
    # ### end Alembic commands ###
