"""empty message

Revision ID: ff10da36fcbd
Revises: d58d17d48044
Create Date: 2024-11-25 19:30:56.774069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff10da36fcbd'
down_revision: Union[str, None] = 'd58d17d48044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Followings',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('int', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['int'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'int')
    )
    op.drop_index('ix_media_id', table_name='media')
    op.drop_table('media')
    op.drop_index('ix_posts_id', table_name='posts')
    op.drop_table('posts')
    op.drop_table('Followers')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Followers',
    sa.Column('follower_id', sa.INTEGER(), nullable=False),
    sa.Column('int', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['int'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'int')
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id')
    )
    op.create_index('ix_posts_id', 'posts', ['id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.Column('media_type', sa.VARCHAR(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_media_id', 'media', ['id'], unique=False)
    op.drop_table('Followings')
    # ### end Alembic commands ###
